import{a as w,i as v,S as g}from"./assets/vendor-483db976.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function p(e,r,s){const n="42524024-b4ed13b49ab793108dce16487";try{return(await w.get(`https://pixabay.com/api/?key=${n}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`)).data}catch(t){throw console.error("Error fetching data:",t),t}}function y(e){v.error({title:"",backgroundColor:"#ec5d5d",message:e,position:"topRight"})}function S(e,r,s){const n=e.map(o=>`<li class="gallery-item"><a href="${o.webformatURL}">
        <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
        <div class='comments'>
        <p><b>Likes </b>${o.likes}</p>
        <p><b>Views </b>${o.views}</p>
        <p><b>Comments </b>${o.comments}</p>
        <p><b>Downloads </b>${o.downloads}</p>
        </div>
        </li>`).join("");return r.innerHTML+=n,new g(".gallery a",s).refresh(),n}function $(e){e.style.display="inline-block"}function q(e){e.style.display="none"}function E(e){e.innerHTML=""}const b=document.querySelector("#form"),i=document.querySelector(".loader"),d=document.querySelector(".gallery"),u=document.querySelector(".load-btn"),m=document.querySelector(".end-message");let a,h=15,c="";const f={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:300,widthRatio:.9,scaleImageToRatio:!0};i.style.display="none";document.addEventListener("DOMContentLoaded",()=>{b.addEventListener("submit",async e=>{if(e.preventDefault(),c=document.getElementById("search").value.trim(),!!c){a=1,d.innerHTML="",$(i),E(d);try{const r=await p(c,a,h);L(r)}catch(r){console.error("Error fetching data:",r),y("An error occurred while fetching data. Please try again.")}finally{q(i)}}})});function L(e){if(e.hits.length===0)y("Sorry, there are no images matching your search query. Please try again!");else{d.insertAdjacentHTML("beforeend",S(e.hits,f)),b.reset();const r=(a-1)*h+e.hits.length;new g(".gallery a",f).refresh(),r<e.totalHits?(u.classList.remove("hidden"),m.classList.add("hidden")):(u.classList.add("hidden"),m.classList.remove("hidden"))}}u.addEventListener("click",M);async function M(){a+=1,i.classList.remove("hidden");try{const e=await p(c,a,h);L(e),P()}catch(e){console.error("Error fetching data:",e)}finally{i.classList.add("hidden")}m.classList.add("hidden")}function P(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
